### ISSUE TITLE
[Bug]: Filtering returns only 1 page

### ISSUE THREAD

**Issue by kraftjs** [boxcee/tanglerarity#1]
### Describe the problem:
Filtering a collection returns only 1 page of results, even if the number or matching NFTs is greater than 1 page's worth.

**Comment by boxcee-interview** [comment]
Thanks for reporting this! I've identified the root cause.

**Root cause:** The pagination component on the NFT listing page uses a hardcoded value of 1000 instead of the actual filtered result count. The API already returns a 'filtered' field with the correct count of NFTs matching the current filters, but it is not being used for the pagination count.

**Fix:** Use the 'filtered' count from the API response instead of the hardcoded value, so pagination correctly reflects the actual number of pages for the filtered results.

Opening a PR with the fix.
